apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-sample
  labels:
    app: httpd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd
        image: iamajai/nginx_with_site:site-1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: 
